<a href="https://colab.research.google.com/github/adelinda02/Gen-AI/blob/main/RNN_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

print('Tensorflow: {}'.format(tf.__version__))

plt.rcParams['figure.figsize'] = (16, 10)
plt.rc('font', size=15)

Tensorflow: 2.20.0


In [2]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [3]:
X_data = np.array([[h]], dtype=np.float32)
X_data.shape

(1, 1, 4)

In [4]:
hidden_size = 2
cell = tf.keras.layers.SimpleRNNCell(units=hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(X_data)

print("X_data: {}, shape: {}".format(X_data, X_data.shape))
print("output: {}, shape: {}".format(outputs, outputs.shape))
print("states: {}, shape: {}".format(states, states.shape))

X_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
output: [[[0.6811579  0.38384986]]], shape: (1, 1, 2)
states: [[0.6811579  0.38384986]], shape: (1, 2)


In [5]:
rnn_2 = tf.keras.layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
outputs, states = rnn_2(X_data)

print("X_data: {}, shape: {}".format(X_data, X_data.shape))
print("output: {}, shape: {}".format(outputs, outputs.shape))
print("states: {}, shape: {}".format(states, states.shape))

X_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
output: [[[0.00977819 0.5150408 ]]], shape: (1, 1, 2)
states: [[0.00977819 0.5150408 ]], shape: (1, 2)


In [6]:
X_data = np.array([[h, e, l, l, o]], dtype=np.float32)
X_data.shape

(1, 5, 4)

In [7]:
cell = tf.keras.layers.SimpleRNNCell(units=hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(X_data)

print("X_data: {}, shape: {}\n".format(X_data, X_data.shape))
print("output: {}, shape: {}\n".format(outputs, outputs.shape))
print("states: {}, shape: {}".format(states, states.shape))

X_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4)

output: [[[ 0.26945612 -0.38808826]
  [-0.6194603   0.34854496]
  [ 0.8865889  -0.35270905]
  [-0.23286003 -0.54744506]
  [ 0.5320108   0.86482143]]], shape: (1, 5, 2)

states: [[0.5320108  0.86482143]], shape: (1, 2)


In [8]:
X_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)
X_data.shape

(3, 5, 4)

In [9]:
cell = tf.keras.layers.SimpleRNNCell(units=hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(X_data)

print("X_data: {}, shape: {}\n".format(X_data, X_data.shape))
print("output: {}, shape: {}\n".format(outputs, outputs.shape))
print("states: {}, shape: {}".format(states, states.shape))

X_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4)

output: [[[ 0.6097463  -0.49362224]
  [ 0.7393019   0.0665006 ]
  [ 0.36554402  0.42730516]
  [ 0.17287847 -0.01915991]
  [-0.3639093   0.7164063 ]]

 [[ 0.6028763  -0.5892892 ]
  [ 0.00404207  0.9053976 ]
  [-0.14717856 -0.48088676]
  [ 0.8349698  -0.1826929 ]
  [ 0.5253953   0.5599853 ]]

 [[ 0.6057958  -0.21046545]
  [ 0.59756875  0.4032521 ]
  [ 0.11158653 -0.2506746 ]
  [ 0.71336883 -0.45017272]
  [ 0.70482326  0.5452632 ]]], shape: (3, 5, 2)

states: [[-0.3639093   0.7164063 ]
 [ 0.5253953   0.5599853 ]
 [ 0.70482326  0.5452632 ]], shape: (3, 2)
